algo:
  - DQN
env: MountainCar-v0
sim: 1
epi: 2000
param:
  # q-learning parameters
  gamma: null
  epsilon_fixed: null
  epsilon_start: null
  epsilon_end: null
  epsilon_decay: null

  # rsrs parameters
  epsilon_dash: null
  k: null
  zeta: null
  global_aleph: null
  global_value_size: null
  centroids_decay: null

  # optimizer parameters
  optimizer: null
  adam_learning_rate: null
  rmsprop_learning_rate: null
  rmsprop_alpha: null
  rmsprop_eps: null
  max_grad_norm: null

  # loss function parameters
  criterion: null
  mseloss_reduction: null

  # memory parameters
  replay_buffer_capacity: null
  episodic_memory_capacity: null

  # network parameters
  hidden_size: null
  embedding_size: null
  neighbor_frames: null

  # etc parameters
  sync_model_update: null
  warmup: null
  tau: null
  batch_size: [64]
  target_update_freq: null
