import numpy as np
import matplotlib.pyplot as plt

def save_episode_plot(collector):
    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_epi_list)
    plt.title('Reward')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.reward_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'reward.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_greedy_epi_list)
    plt.title('Reward Greedy')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.reward_greedy_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'reward_greedy.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_sma_epi_list)
    plt.title(f'Reward SMA({collector.sma_window})')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.reward_sma_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'reward_sma.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_greedy_sma_epi_list)
    plt.title(f'Reward Greedy SMA({collector.sma_window})')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.reward_greedy_sma_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'reward_greedy_sma.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_epi_list)
    plt.title('Survived Step')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.survived_step_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'survived_step.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_greedy_epi_list)
    plt.title('Survived Step Greedy')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.survived_step_greedy_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'survived_step_greedy.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_sma_epi_list)
    plt.title(f'Survived Step SMA({collector.sma_window})')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.survived_step_sma_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'survived_step_sma.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_greedy_sma_epi_list)
    plt.title(f'Survived Step Greedy SMA({collector.sma_window})')
    plt.xlabel('Episode')
    plt.xlim(-1, len(collector.survived_step_greedy_sma_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'survived_step_greedy_sma.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.loss_step_list)
    plt.title('Loss')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.loss_step_list) + 1)
    plt.savefig(collector.sim_dir_path + 'loss.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.loss_sma_step_list)
    plt.title(f'Loss SMA({collector.sma_window})')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.loss_sma_step_list) + 1)
    plt.savefig(collector.sim_dir_path + 'loss_sma.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.pi_step_list)
    plt.title('Pi')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.pi_step_list) + 1)
    plt.savefig(collector.sim_dir_path + 'pi.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.q_value_step_list, alpha=0.4)
    plt.title('Q value')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.q_value_step_list) + 1)
    plt.savefig(collector.sim_dir_path + 'q_value.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.terminal_state_ratio_epi_list, alpha=0.4)
    plt.title('Count of done=1 in 1 update')
    plt.xlabel('Count')
    plt.xlim(-1, len(collector.terminal_state_ratio_epi_list) + 1)
    plt.savefig(collector.sim_dir_path + 'terminal_state_ratio.png')
    plt.close()

    states_array = np.array(collector.state_step_list)
    x = states_array[:, 0]
    theta = states_array[:, 2]
    plt.figure(figsize=(6, 6))
    plt.hist2d(x, theta, bins=40, range=[[-4.8, 4.8], [-0.42, 0.42]])
    plt.colorbar(label='Count')
    plt.title(f'State Distribution (Episode {collector.epi})')
    plt.xlabel('Cart Position (x)')
    plt.ylabel('Pole Angle (theta)')
    plt.savefig(collector.sim_dir_path + 'state_x_theta.png')
    plt.close()

    plt.figure(figsize=(6, 6))
    plt.hist(theta, bins=50, range=(-0.5, 0.5))
    plt.colorbar(label='Count')
    plt.title(f'Theta Distribution (Episode {collector.epi})')
    plt.xlabel("Pole Angle (theta)")
    plt.ylabel("Frequency")
    plt.savefig(collector.sim_dir_path + 'state_theta.png')
    plt.close()
