import matplotlib.pyplot as plt

def save_epi1000_plot(collector, epi):
    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_epi_list)
    plt.title(f'Reward epi{epi}')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'reward_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_greedy_epi_list)
    plt.title(f'Reward Greedy epi{epi}')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'reward_greedy_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_sma_epi_list)
    plt.title(f'Reward SMA({collector.sma_window}) epi{epi}')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'reward_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_greedy_sma_epi_list)
    plt.title(f'Reward Greedy SMA({collector.sma_window}) epi{epi}')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'reward_greedy_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_epi_list)
    plt.title(f'Survived Step epi{epi}')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'survived_step_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_greedy_epi_list)
    plt.title(f'Survived Step Greedy epi{epi}')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'survived_step_greedy_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_sma_epi_list)
    plt.title(f'Survived Step SMA({collector.sma_window})')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'survived_step_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_greedy_sma_epi_list)
    plt.title(f'Survived Step Greedy SMA({collector.sma_window})')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.savefig(collector.sim_dir_path + f'survived_step_greedy_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.loss_step_list)
    plt.title(f'Loss epi{epi}')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.loss_step_list) + 1)
    plt.savefig(collector.sim_dir_path + f'loss_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.loss_sma_step_list)
    plt.title(f'Loss SMA({collector.sma_window}) epi{epi}')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.loss_sma_step_list) + 1)
    plt.savefig(collector.sim_dir_path + f'loss_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.pi_step_list)
    plt.title(f'Pi epi{epi}')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.pi_step_list) + 1)
    plt.savefig(collector.sim_dir_path + f'pi_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.q_value_step_list, alpha=0.4)
    plt.title(f'Q value epi{epi}')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.q_value_step_list) + 1)
    plt.savefig(collector.sim_dir_path + f'q_value_epi{epi}.png')
    plt.close()
