import matplotlib.pyplot as plt

def save_epi1000_plot(collector, sim_dir_path, epi):
    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_epi_list, label='Reward')
    plt.title('Reward per Episode')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.legend()
    plt.savefig(sim_dir_path + f'reward_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.reward_sma_epi_list, label='Reward')
    plt.title('Reward per Episode')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.legend()
    plt.savefig(sim_dir_path + f'reward_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_epi_list, label='Survived Step')
    plt.title('Survived Step per Episode')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.legend()
    plt.savefig(sim_dir_path + f'survived_step_epi{epi}.png')
    plt.close()
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.survived_step_sma_epi_list, label='Survived Step')
    plt.title('Survived Step per Episode')
    plt.xlabel('Episode')
    plt.xlim(-1, epi+1)
    plt.legend()
    plt.savefig(sim_dir_path + f'survived_step_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.loss_step_list, label='loss')
    plt.title('Loss per Step')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.loss_step_list) + 1)
    plt.legend()
    plt.savefig(sim_dir_path + f'loss_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.loss_sma_step_list, label='loss')
    plt.title('Loss per Step')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.loss_sma_step_list) + 1)
    plt.legend()
    plt.savefig(sim_dir_path + f'loss_sma_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.q_value_step_list, label='Q_value', alpha=0.4)
    plt.title('Q_value per Step')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.q_value_step_list) + 1)
    plt.legend()
    plt.savefig(sim_dir_path + f'q_value_epi{epi}.png')
    plt.close()

    if not collector.is_aleph_state_in_policy:
        return

    plt.figure(figsize=(12, 8))
    plt.plot(collector.q_value_step_list, label='Q_value')
    plt.plot(collector.aleph_state_step_list, label='Aleph State')
    plt.title('Q_value and Aleph State per Step')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.aleph_state_step_list) + 1)
    plt.legend()
    plt.savefig(sim_dir_path + f'q_value_and_aleph_state_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.aleph_state_step_list, label='Aleph State')
    plt.title('Aleph State per Step')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.aleph_state_step_list) + 1)
    plt.legend()
    plt.savefig(sim_dir_path + f'aleph_state_epi{epi}.png')
    plt.close()

    plt.figure(figsize=(12, 8))
    plt.plot(collector.aleph_beta_step_list, label='Beta')
    plt.title('Aleph Beta per Step')
    plt.xlabel('Step')
    plt.xlim(-1, len(collector.aleph_beta_step_list) + 1)
    plt.legend()
    plt.savefig(sim_dir_path + f'aleph_beta_epi{epi}.png')
    plt.close()
